spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:cloud_architecture
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

info:
  team-name: local-team