spring:
  application:
    name: cloud-architecture
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: cloud-architecture
  team-name: ${team-name:}

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: dummy-bucket